name: RFM_Model_Application
version: 0.1
display_name: RFM_Model_Application
description: This application contains all the flows and actions needed for RFM analysis.
  RFM analysis is a marketing technique used to quantitatively rank and group customers
  based on the recency, frequency and monetary total of their recent transactions
  to identify the best customers and perform targeted marketing campaigns.
state: draft
