unique_name: ColumnDistinctValues
action_reference: ColumnDistinctValues
display_name: ColumnDistinctValues
state: draft
df_tags:
- OutOfBoxProfiling
parameters:
- param_name: df
  df_param_type: table
  display_name: df
  user_input_required: true
- param_name: col
  df_param_type: column
  display_name: col
  user_input_required: true
source_type: python
