name: HyperPersonalizationApplication
version: 0.1
display_name: HyperPersonalizationApplication
description: This application analysis the behaviour of the user in the app in the
  free trial to determine the probability of conversion to a paid subscriber.
state: draft
